### PR TITLE
OPTIM: More efficient matching by reducing boxing/unboxing ops when a precise match wasn't found

### PR DESCRIPTION
**Pull request by plokhotnyuk**

### CODE REVIEW

**Comment by Joseph51D** [comment]
Hi Andriy,

Thanks for your contribution, we'll review this and get back to you next week.

Regards,
Joseph

**Comment by plokhotnyuk** [comment]
A good follow up would be the use of collections that are specialized for primitive types, have less footprint and more efficient CPU usage.

**Comment by Steve51D** [comment]
Hi Andriy,

Just letting you know that we've now merged this change into our internal development branch and it will be included as part of the next release. (In the next couple of weeks)

Thanks,
Steve.

**Comment by plokhotnyuk** [comment]
It seems that this improvement will be greatly appreciated by Java Device Detection users.

Below is a flame graph of CPU usage for `Provider.match` call of latest released version that was measured by Java FlightRecorder in our stage environment. It shows that about half of cycles was spend in boxing of ints:

image

**Comment by ben51degrees** [comment]
Closed with commit cd0d5f44bfe7896d9700ffa2f3dbb9574be91f1f

**Comment by plokhotnyuk** [comment]
@ben51degrees, please explain why? You don't want to see me in your contributor list?

**Comment by ben51degrees** [comment]
@plokhotnyuk Apologies for that, it was not my intention to remove you from the commit. Our release process goes through a private develop branch, and while we try to retain pull request commits through pull request ->private develop -> release ->master, this was overlooked in this release. I will make sure you are credited in the release section for the pull request and the issue you raised, or if this is an issue I can re-release with the correct history?

**Comment by plokhotnyuk** [comment]
@ben51degrees, no problem, I'm happy that new version was released with this improvement. I have asked just to ensure that you are open for open-source contributions.

**Comment by ben51degrees** [comment]
@plokhotnyuk Yes, all our APIs are open source, and it's always good to see people reviewing the code and raising issues. So thanks for the contribution, it's much appreciated, and has prompted us to evaluate whether similar type optimisations can be found elsewhere in the API.

**Pull request closed without merging**
